# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'BeaconFinder' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
   use_frameworks!
   
    pod 'Gloss'
    pod 'Moltin', :git => 'https://github.com/moltin/ios-sdk.git', :branch => 'v2'
    pod 'Stripe'
    pod 'Stripe/ApplePay'

end

